<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <RootNamespace>ERP.Seed</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ERP.Seed\ERP.Seed.csproj" />
      <ProjectReference Include="..\src\commons\AetherFire23.Commons.Composition\AetherFire23.Commons.Composition.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="MoveToCommons\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="CliWrap" Version="3.10.0" />
    </ItemGroup>

</Project>
